# Generated by Django 4.2.1 on 2023-05-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_is_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
